# -*- coding: utf-8 -*-
"""
@author: Stanislav Pavlovich Gamenyuk
"""

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1069, 821)
        MainWindow.setMinimumSize(QtCore.QSize(1069, 821))
        MainWindow.setMaximumSize(QtCore.QSize(1069, 821))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.panelTools = QtWidgets.QFrame(self.centralwidget)
        self.panelTools.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.panelTools.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.panelTools.setObjectName("panelTools")
        self.gridLayout = QtWidgets.QGridLayout(self.panelTools)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(5, 5, 5, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.objLbl = QtWidgets.QLabel(self.panelTools)
        self.objLbl.setMinimumSize(QtCore.QSize(400, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.objLbl.setFont(font)
        self.objLbl.setObjectName("objLbl")
        self.verticalLayout.addWidget(self.objLbl)
        self.objName = QtWidgets.QLabel(self.panelTools)
        self.objName.setMinimumSize(QtCore.QSize(400, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.objName.setFont(font)
        self.objName.setObjectName("objName")
        self.verticalLayout.addWidget(self.objName)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.loadBttn = QtWidgets.QPushButton(self.panelTools)
        self.loadBttn.setMinimumSize(QtCore.QSize(200, 110))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.loadBttn.setFont(font)
        self.loadBttn.setObjectName("loadBttn")
        self.gridLayout.addWidget(self.loadBttn, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.panelTools, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(255, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.imageZone = QtWidgets.QFrame(self.centralwidget)
        self.imageZone.setFrameShape(QtWidgets.QFrame.Box)
        self.imageZone.setFrameShadow(QtWidgets.QFrame.Raised)
        self.imageZone.setObjectName("imageZone")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.imageZone)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.imgLbl = QtWidgets.QLabel(self.imageZone)
        self.imgLbl.setMinimumSize(QtCore.QSize(624, 430))
        self.imgLbl.setStyleSheet("")
        self.imgLbl.setText("")
        self.imgLbl.setTextFormat(QtCore.Qt.AutoText)
        self.imgLbl.setScaledContents(True)
        self.imgLbl.setWordWrap(False)
        self.imgLbl.setIndent(-1)
        self.imgLbl.setOpenExternalLinks(False)
        self.imgLbl.setObjectName("imgLbl")
        self.gridLayout_3.addWidget(self.imgLbl, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.imageZone, 1, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 620, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 1, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1069, 21))
        self.menubar.setObjectName("menubar")
        self.file_menu = QtWidgets.QMenu(self.menubar)
        self.file_menu.setObjectName("file_menu")
        self.help_menu = QtWidgets.QMenu(self.menubar)
        self.help_menu.setObjectName("help_menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.openAction = QtWidgets.QAction(MainWindow)
        self.openAction.setObjectName("openAction")
        self.saveAction = QtWidgets.QAction(MainWindow)
        self.saveAction.setObjectName("saveAction")
        self.exitAction = QtWidgets.QAction(MainWindow)
        self.exitAction.setObjectName("exitAction")
        self.file_menu.addAction(self.openAction)
        self.file_menu.addSeparator()
        self.file_menu.addAction(self.exitAction)
        self.menubar.addAction(self.file_menu.menuAction())
        self.menubar.addAction(self.help_menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.objLbl.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt;\">Объект</span></p></body></html>"))
        self.objName.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.loadBttn.setText(_translate("MainWindow", "Загрузить"))
        self.file_menu.setTitle(_translate("MainWindow", "Файл"))
        self.help_menu.setTitle(_translate("MainWindow", "Помощь"))
        self.openAction.setText(_translate("MainWindow", "Открыть"))
        self.saveAction.setText(_translate("MainWindow", "Сохранить"))
        self.exitAction.setText(_translate("MainWindow", "Выход"))
